name: Greetings

on:
  #triggers the workflow on pull requests events for master branch
  
  pull_request:
    branches: [master]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        #issue-message: 'Hi, thanks for the improvement'
        pr-message: 'Hi, THANKS for the improvement!'
